site_name: "FIWARE Big Bang"
site_description: FIWARE Big Bang (Let's FIWARE)

nav:
  - 'Home':
    - 'Index': index.md
    - 'Install': install.md
    - 'Cygnus': cygnus.md
    - 'Node-RED': node-red.md
