version: "3"
services:
  iot-agent:
    image: ${IMAGE_IOTAGENT}
    depends_on:
      - mongo
      # __IOTA_DEPENDS_ON__
    ports:
      - 4041:4041
    environment:
      - IOTA_CB_HOST=orion
      - IOTA_CB_PORT=1026
      - IOTA_NORTH_PORT=4041
      - IOTA_REGISTRY_TYPE=mongodb
      - IOTA_LOG_LEVEL=DEBUG
      - IOTA_TIMESTAMP=true
      - IOTA_CB_NGSI_VERSION=v2
      - IOTA_AUTOCAST=true
      - IOTA_MONGO_HOST=mongo
      - IOTA_MONGO_PORT=27017
      - IOTA_MONGO_DB=iotagentul
      - IOTA_DEFAULT_RESOURCE=
      - IOTA_PROVIDER_URL=http://iot-agent:4041
      # __IOTA_ENVIRONMENT__
    restart: always
    logging:
      driver: syslog
      options:
        tag: "[iotagent]"
