version: "3"
services:
  mongo:
    image: ${IMAGE_MONGO}
    command: --nojournal
    volumes:
      - ./config/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./data/mongo-data:/data/db
    restart: always
    logging:
      driver: syslog
      options:
        tag: "[mongo]"
