version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    depends_on:
      - orion
      - keyrock
      - wilma
      - tokenproxy
      # __NGINX_DEPENDS_ON__
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/sites-enable:/etc/nginx/sites-enable
      - ${CERT_DIR}:/etc/letsencrypt
      - ${NGINX_LOG_DIR}:/var/log/nginx
      # __NGINX_VOLUMES__
    restart: always
    logging:
      driver: syslog
      options:
        tag: "[nginx]"

  orion:
    image: telefonicaiot/fiware-orion:3.2.0
    depends_on:
      - mongo
    entrypoint: ["sh", "-c", "rm /tmp/contextBroker.pid; /usr/bin/contextBroker -fg -multiservice -dbhost mongo"]
    restart: always
    logging:
      driver: syslog
      options:
        tag: "[orion]"

  mongo:
    image: mongo:4.4
    command: --nojournal
    volumes:
      - ./config/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always
    logging:
      driver: syslog
      options:
        tag: "[mongo]"

  keyrock:
    image: fiware/idm:8.0.0
    depends_on:
      - mysql
    environment:
      - IDM_HOST=${IDM_HOST}
      - IDM_PORT=3000
      - IDM_DB_HOST=${IDM_DB_HOST}
      - IDM_DB_NAME=${IDM_DB_NAME}
      - IDM_DB_USER=${IDM_DB_USER}
      - IDM_DB_PASS=${IDM_DB_PASS}
      - IDM_ADMIN_UID=${IDM_ADMIN_UID}
      - IDM_ADMIN_USER=${IDM_ADMIN_USER}
      - IDM_ADMIN_EMAIL=${IDM_ADMIN_EMAIL}
      - IDM_ADMIN_PASS=${IDM_ADMIN_PASS}
      - IDM_SESSION_SECRET=${IDM_SESSION_SECRET}
      - IDM_ENCRYPTION_KEY=${IDM_ENCRYPTION_KEY}
      - IDM_DEBUG=true
    restart: always
    logging:
      driver: syslog
      options:
        tag: "[keyrock]"

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data/mysql-data:/var/lib/mysql
    restart: always
    logging:
      driver: syslog
      options:
        tag: "[mysql]"

  wilma:
    image: fiware/pep-proxy:8.0.0
    depends_on:
      - keyrock
    environment:
      - PEP_PROXY_DEBUG=true
      - PEP_PROXY_PORT=1026
      - PEP_PROXY_IDM_HOST=keyrock
      - PEP_PROXY_IDM_PORT=3000
      - PEP_PROXY_APP_ID=${PEP_PROXY_APP_ID}
      - PEP_PROXY_USERNAME=${PEP_PROXY_USERNAME}
      - PEP_PASSWORD=${PEP_PASSWORD}
      - PEP_PROXY_AUTH_FOR_NGINX=true
    restart: always
    logging:
      driver: syslog
      options:
        tag: "[pep-proxy]"

  tokenproxy:
    image: letsfiware/tokenproxy:1.0
    build: ./config/tokenproxy
    depends_on:
      - keyrock
    restart: always
    logging:
      driver: syslog
      options:
        tag: "[tokenproxy]"
    command: >
      --config
      ./ngsi-go-config.json
      --cache
      ./ngsi-go-token-cache.json
      tokenproxy
      server
      --idmHost
      http://keyrock:3000
      --clientId
      ${CLIENT_ID}
      --clientSecret
      ${CLIENT_SECRET}
      --verbose

