services:
  mysql:
    image: ${IMAGE_MYSQL}
    # __MYSQL_PORTS__
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data/mysql-data:/var/lib/mysql
    restart: always
    logging:
      driver: syslog
      options:
        tag: "[mysql]"
