services:
  nginx:
    image: ${IMAGE_NGINX}
    ports:
      - 80:80
      - 443:443
    # __NGINX_PORTS__
    depends_on:
    # __NGINX_DEPENDS_ON__
    volumes:
      - ${CONFIG_NGINX}/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${CONFIG_NGINX}/sites-enable:/etc/nginx/sites-enable
      - ${CONFIG_NGINX}/fullchain.pem:/etc/nginx/fullchain.pem:ro
      - ${CONFIG_NGINX}/privkey.pem:/etc/nginx/privkey.pem:ro
      - ${CERTBOT_DIR}:/var/www/html
      - ${CERT_DIR}:/etc/letsencrypt
      - ${NGINX_LOG_DIR}:/var/log/nginx
      # __NGINX_VOLUMES__
    restart: always
    logging:
      driver: syslog
      options:
        tag: "[nginx]"
