version: "3"
services:
  zeppelin:
    image: ${IMAGE_ZEPPELIN}
    volumes:
      - ./data/zeppelin/conf:/opt/zeppelin/conf
      - ./data/zeppelin/notebook:/opt/zeppelin/notebook
    logging:
      driver: syslog
      options:
        tag: "[zeppelin]"
