services:
  comet:
    image: ${IMAGE_COMET}
    init: true
    # __COMET_PORTS__
    depends_on:
      # __COMET_DEPENDS_ON__
      - mongo
    networks:
      - default
    environment:
      - STH_HOST=0.0.0.0
      - STH_PORT=8666
      - DB_PREFIX=sth_
      - DB_URI=mongo:27017
      - LOGOPS_LEVEL=${COMET_LOGOPS_LEVEL}
    healthcheck:
      test: curl --fail -s http://comet:8666/version || exit 1
    restart: always
    logging:
      driver: syslog
      options:
        tag: "[comet]"
