services:
  tokenproxy:
    image: ${IMAGE_TOKENPROXY}
    # __TOKENPROXY_DEPENDS_ON__
    environment:
      - HOST=${TOKENPROXY_KEYROCK}
      - CLIENT_ID=${TOKENPROXY_CLIENT_ID}
      - CLIENT_SECRET=${TOKENPROXY_CLIENT_SECRET}
      - VERBOSE=${TOKENPROXY_VERBOSE}
    restart: always
    logging:
      driver: syslog
      options:
        tag: "[tokenproxy]"
