version: "3"
services:
  postgres:
    image: ${IMAGE_POSTGRES}
    # __POSTGRES_PORTS__
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    restart: always
    logging:
      driver: syslog
      options:
        tag: "[postgres]"
