services:
  orion:
    image: ${IMAGE_ORION}
    # __ORION_PORTS__
    depends_on:
      - mongo
    # __ORION_DEPENDS_ON__
    entrypoint: ["sh", "-c", "if [ -e /tmp/contextBroker.pid ]; then rm /tmp/contextBroker.pid; fi; /usr/bin/contextBroker -fg -multiservice -ngsiv1Autocast -disableFileLog -dbURI mongodb://mongo"]
    restart: always
    logging:
      driver: syslog
      options:
        tag: "[orion]"
