name: setup tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-test:
    name: setup test

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run setup test
      run: make setup-test
