name: Yamllint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  yamllint:
    name: yamllint

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install shellcheck
      run: sudo apt install -y yamllint

    - name: Run shellcheck
      run: ./test/script/lint-yamllint.sh
